### ISSUE TITLE
Include Azure CLI

### ISSUE THREAD

**Issue by madstt** [pulumi/ci-workflow-templates#12]
I've tried to get the Bitbucket Pipelines to work, it can find the Pulumi dependency, but not Azure CLI:

````
error: building auth config: obtain subscription() from Azure CLI: Error parsing json result from the Azure CLI: Error launching Azure CLI: exec: "az": executable file not found in $PATH
````
 The included `pulumi/pulumi-dotnet:latest` image does not include the Azure CLI, which is a prerequisite. I've tested using the [`microsoft/azure-cli-run:1.1.0`](https://bitbucket.org/microsoft/azure-cli-run/src/master/) pipe, but this pipe only allows `az` commands. Then I've tried to use the `mcr.microsoft.com/azure-cli` image, like this:

````
  name: Run AZ script
  image: mcr.microsoft.com/azure-cli
  script:
    - *vars
    - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD -t $AZURE_TENANT_ID
    - pulumi up --yes --cwd ${PULUMI_WORKING_DIRECTORY} -s ${PULUMI_STACK_NAME}

````
This would override the Pulumi image, and not be able to use Pulumi.

So, how do I get Pulumi to run in a Bitbucket Pipelines?
